# Generated by Django 5.0.7 on 2026-04-01 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('full_payment', 'Full Payment'), ('deposit', 'Deposit')], default='full_payment', max_length=20),
        ),
    ]
