# Generated by Django 5.0.7 on 2025-12-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_payment_currency_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chefpayout',
            options={'ordering': ['-created_at'], 'verbose_name': 'chef payout', 'verbose_name_plural': 'chef payouts'},
        ),
        migrations.AlterModelOptions(
            name='mpesapayment',
            options={'ordering': ['-created_at'], 'verbose_name': 'M-Pesa payment', 'verbose_name_plural': 'M-Pesa payments'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name': 'payment', 'verbose_name_plural': 'payments'},
        ),
        migrations.AlterModelOptions(
            name='refund',
            options={'ordering': ['-created_at'], 'verbose_name': 'refund', 'verbose_name_plural': 'refunds'},
        ),
        migrations.RemoveField(
            model_name='chefpayout',
            name='stripe_transfer_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='paystack_reference',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='stripe_charge_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='stripe_payment_intent_id',
        ),
        migrations.RemoveField(
            model_name='refund',
            name='stripe_refund_id',
        ),
        migrations.AlterField(
            model_name='chefpayout',
            name='currency',
            field=models.CharField(default='KES', max_length=3),
        ),
    ]
