# Generated by Django 6.0.1 on 2026-01-25 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "payments",
            "0005_alter_chefpayout_options_alter_mpesapayment_options_and_more",
        ),
        ("users", "0007_businessaccount_alter_clientprofile_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="business",
            field=models.ForeignKey(
                blank=True,
                db_column="business_id",
                help_text="Business account payment",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="users.businessaccount",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="client",
            field=models.ForeignKey(
                blank=True,
                db_column="client_id",
                help_text="Individual client payment",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="individual_payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterModelTable(
            name="payment",
            table="payments_payment",
        ),
    ]
