# Generated by Django 5.2.8 on 2026-03-28 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientonboarding",
            name="allergies_details",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="allergies_details",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="budget_range",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="dining_frequency",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="location",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="occasion_types",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
