# Generated by Django 5.2.8 on 2025-11-28 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("client", "Client"),
                    ("chef", "Chef"),
                    ("farmer", "Farmer"),
                    ("business", "Business"),
                    ("admin", "Admin"),
                ],
                default="client",
                max_length=10,
            ),
        ),
    ]
