# Generated by Django 6.0.1 on 2026-01-26 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_businessaccount_alter_clientprofile_options_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="user",
            table=None,
        ),
    ]
