# Generated by Django 6.0.1 on 2026-01-26 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_user_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="businessmember",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "business member",
                "verbose_name_plural": "business members",
            },
        ),
        migrations.RenameField(
            model_name="businessaccount",
            old_name="business_email",
            new_name="billing_email",
        ),
        migrations.RenameField(
            model_name="businessaccount",
            old_name="billing_address",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="businessaccount",
            old_name="company_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="businessmember",
            old_name="joined_at",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="clientprofile",
            old_name="address",
            new_name="default_address",
        ),
        migrations.RenameField(
            model_name="clientprofile",
            old_name="total_spend",
            new_name="total_spent",
        ),
        migrations.RemoveField(
            model_name="businessaccount",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="businessaccount",
            name="tax_id",
        ),
        migrations.RemoveField(
            model_name="businessaccount",
            name="total_bookings",
        ),
        migrations.RemoveField(
            model_name="businessaccount",
            name="total_spend",
        ),
        migrations.RemoveField(
            model_name="businessaccount",
            name="verification_status",
        ),
        migrations.RemoveField(
            model_name="clientprofile",
            name="allergies",
        ),
        migrations.RemoveField(
            model_name="clientprofile",
            name="dietary_preferences",
        ),
        migrations.RemoveField(
            model_name="clientprofile",
            name="emergency_contact",
        ),
        migrations.RemoveField(
            model_name="clientprofile",
            name="emergency_phone",
        ),
        migrations.RemoveField(
            model_name="clientprofile",
            name="last_booking_date",
        ),
        migrations.RemoveField(
            model_name="clientprofile",
            name="preferred_cuisines",
        ),
        migrations.AddField(
            model_name="businessaccount",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="businessaccount",
            name="logo_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="businessaccount",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="businessmember",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="full_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="preferences",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="profile_image",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="clientprofile",
            name="user",
            field=models.OneToOneField(
                db_column="user_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
