# Generated by Django 6.0.1 on 2026-01-26 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_businessmember_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clientprofile",
            name="id",
        ),
        migrations.AlterField(
            model_name="clientprofile",
            name="user",
            field=models.OneToOneField(
                db_column="user_id",
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="client_profile",
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
