# Generated by Django 5.2.8 on 2026-03-26 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0003_initial"),
        ("chefs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="chefonboarding",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chef_onboarding",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="chefprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chef_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="chefevent",
            name="chef",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="chefs.chefprofile",
            ),
        ),
        migrations.AddField(
            model_name="chefcertification",
            name="chef",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chef_certifications",
                to="chefs.chefprofile",
            ),
        ),
        migrations.AddField(
            model_name="chefreview",
            name="booking",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review",
                to="bookings.booking",
            ),
        ),
        migrations.AddField(
            model_name="chefreview",
            name="chef",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="chefs.chefprofile",
            ),
        ),
        migrations.AddField(
            model_name="chefreview",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chef_reviews_given",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="favoritechef",
            name="chef",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorited_by",
                to="chefs.chefprofile",
            ),
        ),
        migrations.AddField(
            model_name="favoritechef",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorite_chefs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="chefreview",
            unique_together={("chef", "client", "booking")},
        ),
        migrations.AlterUniqueTogether(
            name="favoritechef",
            unique_together={("user", "chef")},
        ),
    ]
