# Generated by Django 5.0.7 on 2026-04-01 06:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0003_chefprofile_culinary_paths_and_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='chefreview',
            name='platform_rating',
            field=models.PositiveIntegerField(blank=True, help_text='How would you rate the Foodie platform experience?', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
