# Generated by Django 5.0.7 on 2025-12-05 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0004_chefevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chefprofile',
            options={'ordering': ['-average_rating', '-total_bookings'], 'verbose_name': 'chef profile', 'verbose_name_plural': 'chef profiles'},
        ),
    ]
