# Generated by Django 5.2.8 on 2026-01-02 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chefs", "0005_alter_chefprofile_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChefOnboarding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("culinary_paths", models.JSONField(blank=True, default=list)),
                ("specialties", models.JSONField(blank=True, default=list)),
                ("experience_level", models.CharField(blank=True, max_length=50)),
                ("portfolio_media", models.JSONField(blank=True, default=list)),
                ("availability_options", models.JSONField(blank=True, default=list)),
                ("pricing_tier", models.CharField(blank=True, max_length=50)),
                ("certifications", models.JSONField(blank=True, default=list)),
                (
                    "identity_verification_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("completed", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chef_onboarding",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
