# Generated by Django 6.0.1 on 2026-01-26 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chefs", "0006_chefonboarding"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="chefprofile",
            table="chefs_chefprofile",
        ),
    ]
