# Generated by Django 5.0.7 on 2025-12-05 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chatroom_booking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatroom',
            options={'ordering': ['-updated_at'], 'verbose_name': 'chat room', 'verbose_name_plural': 'chat rooms'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_at'], 'verbose_name': 'message', 'verbose_name_plural': 'messages'},
        ),
        migrations.AlterModelOptions(
            name='messagereadstatus',
            options={'verbose_name': 'message read status', 'verbose_name_plural': 'message read statuses'},
        ),
    ]
