# Generated by Django 5.2.8 on 2026-03-27 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "short_description",
                    models.CharField(
                        blank=True,
                        help_text="Short tagline shown on cards",
                        max_length=120,
                    ),
                ),
                ("image", models.URLField(blank=True, max_length=500)),
                (
                    "icon_emoji",
                    models.CharField(blank=True, default="🍽️", max_length=10),
                ),
                (
                    "price_from",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Lowest per-person price from approved menus, used for display",
                        max_digits=10,
                    ),
                ),
                ("price_display", models.CharField(blank=True, max_length=80)),
                ("min_guests", models.PositiveIntegerField(default=1)),
                ("guest_display", models.CharField(blank=True, max_length=60)),
                ("available_chef_count", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower = shown first"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "experience",
                "verbose_name_plural": "experiences",
                "ordering": ["display_order", "name"],
            },
        ),
    ]
