# Generated by Django 5.0.7 on 2026-03-31 10:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('kcal', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('cuisine_type', models.CharField(blank=True, max_length=100, null=True)),
                ('dietary_tags', models.JSONField(blank=True, default=list)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_bookings', models.PositiveIntegerField(default=0)),
                ('average_rating', models.FloatField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='experience',
            name='image',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='min_guests',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='price_from',
        ),
        migrations.AddField(
            model_name='experience',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='experience',
            name='status',
            field=models.CharField(default='published', max_length=50),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='experience',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price_per_person', models.DecimalField(decimal_places=2, max_digits=10)),
                ('guest_min', models.PositiveIntegerField(default=1)),
                ('guest_max', models.PositiveIntegerField(blank=True, null=True)),
                ('dietary_tags', models.JSONField(blank=True, default=list)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('status', models.CharField(default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_menus', to='experiences.experience')),
            ],
        ),
        migrations.CreateModel(
            name='MenuMeal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_type', models.CharField(blank=True, max_length=50, null=True)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experiences.meal')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experiences.menu')),
            ],
            options={
                'ordering': ['order_index'],
                'unique_together': {('menu', 'meal', 'order_index')},
            },
        ),
        migrations.AddField(
            model_name='menu',
            name='meals',
            field=models.ManyToManyField(related_name='menus', through='experiences.MenuMeal', to='experiences.meal'),
        ),
    ]
