-- ============================================================================
-- Foodie v2 - Database Cleanup & Alignment Script (v6)
-- Purpose: Remove redundancy, enforce architectural constraints, and align types.
-- ============================================================================

-- 1. CLEAN UP REDUNDANT COLUMNS
DO $$
BEGIN
    ALTER TABLE IF EXISTS public.users_user DROP COLUMN IF EXISTS supabase_user_id;
    ALTER TABLE IF EXISTS public.clients_clientprofile DROP COLUMN IF EXISTS supabase_user_id;
    ALTER TABLE IF EXISTS public.chefs_chefprofile DROP COLUMN IF EXISTS supabase_user_id;
    ALTER TABLE IF EXISTS public.chefs_chefonboarding DROP COLUMN IF EXISTS supabase_user_id;
    ALTER TABLE IF EXISTS public.business_members DROP COLUMN IF EXISTS supabase_user_id;
END $$;

-- 2. ENFORCE XOR CONSTRAINTS (CLIENT OR BUSINESS)
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'bookings_booking') THEN
        ALTER TABLE public.bookings_booking DROP CONSTRAINT IF EXISTS booking_client_or_business_check;
        ALTER TABLE public.bookings_booking ADD CONSTRAINT booking_client_or_business_check CHECK (
            (client_user_id IS NOT NULL AND business_id IS NULL) OR
            (client_user_id IS NULL AND business_id IS NOT NULL)
        );
    END IF;
END $$;

-- 3. ENSURE ALL TABLES EXIST AND ALIGN FK TYPES
-- Since multiple tables were missing but migrations were applied, we recreate them.

-- Payment table
CREATE TABLE IF NOT EXISTS public.payments_payment (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount numeric(10, 2) NOT NULL,
    currency varchar(3) DEFAULT 'KES' NOT NULL,
    status varchar(20) DEFAULT 'pending' NOT NULL,
    payment_method varchar(50) DEFAULT 'mpesa' NOT NULL,
    transaction_id varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL,
    processed_at timestamptz,
    booking_id uuid REFERENCES public.bookings_booking(id),
    client_id uuid REFERENCES public.users_user(id),
    business_id bigint REFERENCES public.business_accounts(id),
    platform_fee numeric(8, 2) DEFAULT 0.00,
    processing_fee numeric(8, 2) DEFAULT 0.00,
    chef_payout numeric(10, 2) DEFAULT 0.00,
    payment_metadata jsonb DEFAULT '{}'::jsonb,
    failure_reason text DEFAULT ''
);

-- Refund table
CREATE TABLE IF NOT EXISTS public.payments_refund (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount numeric(10, 2) NOT NULL,
    reason text NOT NULL,
    status varchar(20) DEFAULT 'pending' NOT NULL,
    refund_type varchar(20) DEFAULT 'full' NOT NULL,
    external_refund_id varchar(200),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL,
    processed_at timestamptz,
    booking_id uuid REFERENCES public.bookings_booking(id),
    payment_id bigint REFERENCES public.payments_payment(id),
    processed_by_id uuid REFERENCES public.users_user(id),
    admin_notes text DEFAULT ''
);

-- ChefPayout table
CREATE TABLE IF NOT EXISTS public.payments_chefpayout (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount numeric(10, 2) NOT NULL,
    currency varchar(3) DEFAULT 'KES' NOT NULL,
    status varchar(20) DEFAULT 'pending' NOT NULL,
    bank_account_number varchar(50),
    bank_routing_number varchar(20),
    bank_name varchar(100),
    external_payout_id varchar(200),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL,
    processed_at timestamptz,
    booking_id uuid REFERENCES public.bookings_booking(id),
    chef_id uuid REFERENCES public.users_user(id),
    payment_id bigint REFERENCES public.payments_payment(id),
    processed_by_id uuid REFERENCES public.users_user(id),
    admin_notes text DEFAULT ''
);

-- ChefReview table
CREATE TABLE IF NOT EXISTS public.chefs_chefreview (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rating integer NOT NULL,
    comment text DEFAULT '',
    food_quality integer,
    professionalism integer,
    punctuality integer,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL,
    booking_id uuid UNIQUE REFERENCES public.bookings_booking(id),
    chef_id uuid REFERENCES public.users_user(id),
    client_id uuid REFERENCES public.users_user(id)
);

-- ChefCertification table
CREATE TABLE IF NOT EXISTS public.chefs_chefcertification (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(200) NOT NULL,
    issuing_organization varchar(200) NOT NULL,
    issue_date date NOT NULL,
    expiry_date date,
    certificate_image varchar(255),
    is_verified boolean DEFAULT false,
    created_at timestamptz DEFAULT now() NOT NULL,
    chef_id uuid REFERENCES public.users_user(id)
);

-- MpesaPayment table
CREATE TABLE IF NOT EXISTS public.payments_mpesapayment (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone_number varchar(15) NOT NULL,
    checkout_request_id varchar(255) UNIQUE NOT NULL,
    merchant_request_id varchar(255) NOT NULL,
    mpesa_receipt_number varchar(255),
    transaction_date varchar(20),
    status varchar(20) DEFAULT 'pending' NOT NULL,
    failure_reason text,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL,
    payment_id bigint UNIQUE REFERENCES public.payments_payment(id)
);

-- BookingMenuItem
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'bookings_bookingmenuitem') THEN
        ALTER TABLE public.bookings_bookingmenuitem DROP COLUMN IF EXISTS booking_id;
        ALTER TABLE public.bookings_bookingmenuitem ADD COLUMN booking_id uuid REFERENCES public.bookings_booking(id);
    END IF;
END $$;

-- ChatRoom
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'chat_chatroom') THEN
        ALTER TABLE public.chat_chatroom DROP COLUMN IF EXISTS booking_id;
        ALTER TABLE public.chat_chatroom ADD COLUMN booking_id uuid REFERENCES public.bookings_booking(id);
    END IF;
END $$;

-- AI ChatSession (booking_context_id)
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'ai_chatsession') THEN
        ALTER TABLE public.ai_chatsession DROP COLUMN IF EXISTS booking_context_id;
        ALTER TABLE public.ai_chatsession ADD COLUMN booking_context_id uuid REFERENCES public.bookings_booking(id);
    END IF;
END $$;

-- 4. ALIGN CONSTRAINTS
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'chefs_chefonboarding') THEN
        ALTER TABLE public.chefs_chefonboarding DROP CONSTRAINT IF EXISTS identity_verification_status_check;
        ALTER TABLE public.chefs_chefonboarding ADD CONSTRAINT identity_verification_status_check CHECK (
            identity_verification_status IN ('pending', 'verified', 'rejected')
        );
    END IF;
END $$;

SELECT 'Cleanup & Re-creation (v6) complete' as status;
