-- ============================================================================
-- Foodie v2 - Supabase Client & Business Account Schema
-- ============================================================================
-- This schema integrates Supabase Auth (UUID-based users) with Django backend
-- Supports both B2C (individual clients) and B2B (business accounts)
-- Execute this in: Supabase SQL Editor
-- ============================================================================

-- ============================================================================
-- 1. EXTENSIONS
-- ============================================================================

-- Enable UUID generation (should already be enabled with Supabase Auth)
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================================================
-- 2. CLIENT PROFILE TABLE
-- ============================================================================
-- Purpose: Extend Supabase authenticated users into "clients" 
-- who can make bookings and have preferences
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.clients_clientprofile (
    -- Primary key is the user's UUID from auth.users
    user_id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    
    -- Profile & Preferences
    dietary_preferences jsonb DEFAULT '[]'::jsonb,
    allergies jsonb DEFAULT '[]'::jsonb,
    preferred_cuisines jsonb DEFAULT '[]'::jsonb,
    
    -- Location
    address text,
    city varchar(100),
    state varchar(100),
    zip_code varchar(20),
    
    -- Emergency Contact
    emergency_contact varchar(100),
    emergency_phone varchar(17),
    
    -- Analytics (rolled up from bookings)
    total_bookings integer DEFAULT 0 NOT NULL,
    total_spend numeric(12, 2) DEFAULT 0.00 NOT NULL,
    last_booking_date timestamptz,
    
    -- Timestamps
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_clientprofile_city ON public.clients_clientprofile(city);
CREATE INDEX IF NOT EXISTS idx_clientprofile_last_booking ON public.clients_clientprofile(last_booking_date DESC);

-- ============================================================================
-- 3. BUSINESS ACCOUNTS TABLE
-- ============================================================================
-- Purpose: Represent companies/organizations that can make bookings
-- Note: Uses bigint PK (not UUID) - is an independent entity, not a user
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.business_accounts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- Company Information
    company_name varchar(200) NOT NULL,
    business_email varchar(254) NOT NULL,
    phone_number varchar(17),
    
    -- Address
    address text,
    city varchar(100),
    state varchar(100),
    zip_code varchar(20),
    
    -- Business Details
    tax_id varchar(50),
    billing_address text,
    
    -- Verification
    is_verified boolean DEFAULT false NOT NULL,
    verification_status varchar(20) DEFAULT 'pending' NOT NULL,
    
    -- Analytics
    total_bookings integer DEFAULT 0 NOT NULL,
    total_spend numeric(12, 2) DEFAULT 0.00 NOT NULL,
    
    -- Timestamps
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL,
    
    -- Constraints
    CONSTRAINT verification_status_check CHECK (
        verification_status IN ('pending', 'verified', 'rejected')
    )
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_business_company_name ON public.business_accounts(company_name);
CREATE INDEX IF NOT EXISTS idx_business_email ON public.business_accounts(business_email);
CREATE INDEX IF NOT EXISTS idx_business_verified ON public.business_accounts(is_verified);

-- ============================================================================
-- 4. BUSINESS MEMBERS JUNCTION TABLE
-- ============================================================================
-- Purpose: Define which users belong to which businesses and their roles
-- This is the authorization backbone for B2B functionality
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.business_members (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- Foreign Keys
    business_id bigint NOT NULL REFERENCES public.business_accounts(id) ON DELETE CASCADE,
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    
    -- Role & Permissions
    role varchar(20) DEFAULT 'member' NOT NULL,
    
    -- Timestamp
    joined_at timestamptz DEFAULT now() NOT NULL,
    
    -- Constraints
    CONSTRAINT business_members_unique UNIQUE (business_id, user_id),
    CONSTRAINT role_check CHECK (role IN ('owner', 'admin', 'member'))
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_business_members_business ON public.business_members(business_id);
CREATE INDEX IF NOT EXISTS idx_business_members_user ON public.business_members(user_id);
CREATE INDEX IF NOT EXISTS idx_business_members_role ON public.business_members(role);

-- ============================================================================
-- 5. USERS TABLE (Sync with auth.users)
-- ============================================================================
-- Purpose: Mirror essential user data from auth.users for Django compatibility
-- Note: This is a VIEW or separate table that Django uses
-- ============================================================================

-- Option A: Create a view (recommended)
CREATE OR REPLACE VIEW public.users_user AS
SELECT 
    id,
    email,
    created_at,
    updated_at,
    email as username,  -- Django expects username
    raw_user_meta_data->>'first_name' as first_name,
    raw_user_meta_data->>'last_name' as last_name,
    raw_user_meta_data->>'role' as role,
    raw_user_meta_data->>'phone_number' as phone_number,
    raw_user_meta_data->>'profile_picture' as profile_picture,
    COALESCE((raw_user_meta_data->>'is_verified')::boolean, false) as is_verified
FROM auth.users;

-- ============================================================================
-- 6. UPDATE BOOKINGS TABLE
-- ============================================================================
-- Purpose: Support both individual client bookings AND business bookings
-- ============================================================================

-- First, check if bookings table exists, if not create it
CREATE TABLE IF NOT EXISTS public.bookings_booking (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- EITHER client_user_id OR business_id must be set, but NOT both
    client_user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
    business_id bigint REFERENCES public.business_accounts(id) ON DELETE CASCADE,
    
    -- Chef reference (assuming chefs_chefprofile table exists)
    chef_id bigint NOT NULL,
    
    -- Booking Details
    service_type varchar(20) DEFAULT 'personal_meal' NOT NULL,
    booking_date timestamptz NOT NULL,
    duration_hours integer DEFAULT 2 NOT NULL,
    number_of_guests integer DEFAULT 1 NOT NULL,
    
    -- Location
    service_address text NOT NULL,
    service_city varchar(100) NOT NULL,
    service_state varchar(100) NOT NULL,
    service_zip_code varchar(20) NOT NULL,
    
    -- Menu & Preferences
    dietary_requirements jsonb DEFAULT '[]'::jsonb,
    special_requests text,
    
    -- Pricing
    base_price numeric(10, 2) NOT NULL,
    additional_fees numeric(10, 2) DEFAULT 0.00 NOT NULL,
    total_amount numeric(10, 2) NOT NULL,
    
    -- Priority
    is_priority boolean DEFAULT false NOT NULL,
    down_payment_amount numeric(10, 2) DEFAULT 0.00 NOT NULL,
    
    -- Status
    status varchar(20) DEFAULT 'pending' NOT NULL,
    confirmation_code varchar(20) UNIQUE,
    
    -- Notes
    client_notes text,
    chef_notes text,
    admin_notes text,
    
    -- Timestamps
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL,
    confirmed_at timestamptz,
    completed_at timestamptz,
    cancelled_at timestamptz,
    
    -- CRITICAL CONSTRAINT: Must have either client OR business, not both
    CONSTRAINT booking_client_or_business_check CHECK (
        (client_user_id IS NOT NULL AND business_id IS NULL) OR
        (client_user_id IS NULL AND business_id IS NOT NULL)
    ),
    
    CONSTRAINT status_check CHECK (
        status IN ('pending', 'confirmed', 'in_progress', 'completed', 'cancelled', 'refunded')
    ),
    
    CONSTRAINT service_type_check CHECK (
        service_type IN ('personal_meal', 'event_catering', 'cooking_class', 'meal_prep')
    )
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_bookings_client_user ON public.bookings_booking(client_user_id) WHERE client_user_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_bookings_business ON public.bookings_booking(business_id) WHERE business_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_bookings_chef ON public.bookings_booking(chef_id);
CREATE INDEX IF NOT EXISTS idx_bookings_status ON public.bookings_booking(status);
CREATE INDEX IF NOT EXISTS idx_bookings_date ON public.bookings_booking(booking_date DESC);
CREATE INDEX IF NOT EXISTS idx_bookings_created ON public.bookings_booking(created_at DESC);

-- ============================================================================
-- 7. UPDATE PAYMENTS TABLE
-- ============================================================================
-- Purpose: Support payments from both individual clients and businesses
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.payments_payment (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- Booking reference
    booking_id bigint REFERENCES public.bookings_booking(id) ON DELETE CASCADE,
    
    -- EITHER client OR business (mirrors booking relationship)
    client_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
    business_id bigint REFERENCES public.business_accounts(id) ON DELETE SET NULL,
    
    -- Payment Details
    amount numeric(10, 2) NOT NULL,
    currency varchar(3) DEFAULT 'KES' NOT NULL,
    payment_method varchar(50) DEFAULT 'mpesa' NOT NULL,
    status varchar(20) DEFAULT 'pending' NOT NULL,
    
    -- External Provider
    transaction_id varchar(100),
    
    -- Platform Fees
    platform_fee numeric(8, 2) DEFAULT 0.00 NOT NULL,
    processing_fee numeric(8, 2) DEFAULT 0.00 NOT NULL,
    chef_payout numeric(10, 2) DEFAULT 0.00 NOT NULL,
    
    -- Metadata
    payment_metadata jsonb DEFAULT '{}'::jsonb,
    failure_reason text,
    
    -- Timestamps
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL,
    processed_at timestamptz,
    
    CONSTRAINT payment_status_check CHECK (
        status IN ('pending', 'processing', 'completed', 'failed', 'cancelled', 'refunded', 'partially_refunded')
    )
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_payments_booking ON public.payments_payment(booking_id);
CREATE INDEX IF NOT EXISTS idx_payments_client ON public.payments_payment(client_id) WHERE client_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_payments_business ON public.payments_payment(business_id) WHERE business_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_payments_status ON public.payments_payment(status);

-- ============================================================================
-- 8. ROW LEVEL SECURITY (RLS) POLICIES
-- ============================================================================

-- Enable RLS on all tables
ALTER TABLE public.clients_clientprofile ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.business_accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.business_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bookings_booking ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payments_payment ENABLE ROW LEVEL SECURITY;

-- ============================================================================
-- 8.1 CLIENT PROFILE POLICIES
-- ============================================================================

-- Drop existing policies if any
DROP POLICY IF EXISTS "Users can view own profile" ON public.clients_clientprofile;
DROP POLICY IF EXISTS "Users can update own profile" ON public.clients_clientprofile;
DROP POLICY IF EXISTS "Users can insert own profile" ON public.clients_clientprofile;
DROP POLICY IF EXISTS "Service role full access" ON public.clients_clientprofile;

-- Users can only view their own profile
CREATE POLICY "Users can view own profile" ON public.clients_clientprofile
    FOR SELECT
    USING (auth.uid() = user_id);

-- Users can only update their own profile
CREATE POLICY "Users can update own profile" ON public.clients_clientprofile
    FOR UPDATE
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);

-- Users can insert their own profile
CREATE POLICY "Users can insert own profile" ON public.clients_clientprofile
    FOR INSERT
    WITH CHECK (auth.uid() = user_id);

-- Service role has full access (for Django backend)
CREATE POLICY "Service role full access" ON public.clients_clientprofile
    FOR ALL
    USING (auth.role() = 'service_role');

-- ============================================================================
-- 8.2 BUSINESS ACCOUNTS POLICIES
-- ============================================================================

DROP POLICY IF EXISTS "Members can view their businesses" ON public.business_accounts;
DROP POLICY IF EXISTS "Owners can update business" ON public.business_accounts;
DROP POLICY IF EXISTS "Authenticated can create business" ON public.business_accounts;
DROP POLICY IF EXISTS "Service role full access" ON public.business_accounts;

-- Users can view businesses they are members of
CREATE POLICY "Members can view their businesses" ON public.business_accounts
    FOR SELECT
    USING (
        EXISTS (
            SELECT 1 FROM public.business_members
            WHERE business_members.business_id = business_accounts.id
            AND business_members.user_id = auth.uid()
        )
    );

-- Only owners and admins can update business details
CREATE POLICY "Owners can update business" ON public.business_accounts
    FOR UPDATE
    USING (
        EXISTS (
            SELECT 1 FROM public.business_members
            WHERE business_members.business_id = business_accounts.id
            AND business_members.user_id = auth.uid()
            AND business_members.role IN ('owner', 'admin')
        )
    );

-- Authenticated users can create businesses
CREATE POLICY "Authenticated can create business" ON public.business_accounts
    FOR INSERT
    WITH CHECK (auth.role() = 'authenticated');

-- Service role full access
CREATE POLICY "Service role full access" ON public.business_accounts
    FOR ALL
    USING (auth.role() = 'service_role');

-- ============================================================================
-- 8.3 BUSINESS MEMBERS POLICIES
-- ============================================================================

DROP POLICY IF EXISTS "Members can view business members" ON public.business_members;
DROP POLICY IF EXISTS "Owners can manage members" ON public.business_members;
DROP POLICY IF EXISTS "Service role full access" ON public.business_members;

-- Members can view other members of businesses they belong to
CREATE POLICY "Members can view business members" ON public.business_members
    FOR SELECT
    USING (
        EXISTS (
            SELECT 1 FROM public.business_members bm
            WHERE bm.business_id = business_members.business_id
            AND bm.user_id = auth.uid()
        )
    );

-- Only owners and admins can add/remove members
CREATE POLICY "Owners can manage members" ON public.business_members
    FOR ALL
    USING (
        EXISTS (
            SELECT 1 FROM public.business_members
            WHERE business_members.business_id = business_members.business_id
            AND business_members.user_id = auth.uid()
            AND business_members.role IN ('owner', 'admin')
        )
    );

-- Service role full access
CREATE POLICY "Service role full access" ON public.business_members
    FOR ALL
    USING (auth.role() = 'service_role');

-- ============================================================================
-- 8.4 BOOKINGS POLICIES
-- ============================================================================

DROP POLICY IF EXISTS "Clients view own bookings" ON public.bookings_booking;
DROP POLICY IF EXISTS "Business members view business bookings" ON public.bookings_booking;
DROP POLICY IF EXISTS "Chefs view their bookings" ON public.bookings_booking;
DROP POLICY IF EXISTS "Service role full access" ON public.bookings_booking;

-- Individual clients can view their own bookings
CREATE POLICY "Clients view own bookings" ON public.bookings_booking
    FOR SELECT
    USING (client_user_id = auth.uid());

-- Business members can view their business's bookings
CREATE POLICY "Business members view business bookings" ON public.bookings_booking
    FOR SELECT
    USING (
        business_id IS NOT NULL AND
        EXISTS (
            SELECT 1 FROM public.business_members
            WHERE business_members.business_id = bookings_booking.business_id
            AND business_members.user_id = auth.uid()
        )
    );

-- Service role full access (for Django backend and chef access)
CREATE POLICY "Service role full access" ON public.bookings_booking
    FOR ALL
    USING (auth.role() = 'service_role');

-- ============================================================================
-- 8.5 PAYMENTS POLICIES
-- ============================================================================

DROP POLICY IF EXISTS "Clients view own payments" ON public.payments_payment;
DROP POLICY IF EXISTS "Business members view business payments" ON public.payments_payment;
DROP POLICY IF EXISTS "Service role full access" ON public.payments_payment;

-- Individual clients can view their own payments
CREATE POLICY "Clients view own payments" ON public.payments_payment
    FOR SELECT
    USING (client_id = auth.uid());

-- Business members can view their business's payments
CREATE POLICY "Business members view business payments" ON public.payments_payment
    FOR SELECT
    USING (
        business_id IS NOT NULL AND
        EXISTS (
            SELECT 1 FROM public.business_members
            WHERE business_members.business_id = payments_payment.business_id
            AND business_members.user_id = auth.uid()
        )
    );

-- Service role full access
CREATE POLICY "Service role full access" ON public.payments_payment
    FOR ALL
    USING (auth.role() = 'service_role');

-- ============================================================================
-- 9. TRIGGERS FOR AUTOMATIC TIMESTAMP UPDATES
-- ============================================================================

-- Function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Apply trigger to all tables with updated_at
DROP TRIGGER IF EXISTS update_clientprofile_updated_at ON public.clients_clientprofile;
CREATE TRIGGER update_clientprofile_updated_at
    BEFORE UPDATE ON public.clients_clientprofile
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_business_updated_at ON public.business_accounts;
CREATE TRIGGER update_business_updated_at
    BEFORE UPDATE ON public.business_accounts
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_booking_updated_at ON public.bookings_booking;
CREATE TRIGGER update_booking_updated_at
    BEFORE UPDATE ON public.bookings_booking
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_payment_updated_at ON public.payments_payment;
CREATE TRIGGER update_payment_updated_at
    BEFORE UPDATE ON public.payments_payment
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- ============================================================================
-- 10. GRANT PERMISSIONS
-- ============================================================================

-- Grant necessary permissions to authenticated users
GRANT SELECT, INSERT, UPDATE ON public.clients_clientprofile TO authenticated;
GRANT SELECT, INSERT, UPDATE ON public.business_accounts TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.business_members TO authenticated;
GRANT SELECT ON public.bookings_booking TO authenticated;
GRANT SELECT ON public.payments_payment TO authenticated;

-- Grant full permissions to service role (Django backend)
GRANT ALL ON public.clients_clientprofile TO service_role;
GRANT ALL ON public.business_accounts TO service_role;
GRANT ALL ON public.business_members TO service_role;
GRANT ALL ON public.bookings_booking TO service_role;
GRANT ALL ON public.payments_payment TO service_role;

-- Grant sequence permissions
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;

-- ============================================================================
-- SCHEMA SETUP COMPLETE
-- ============================================================================
-- Next steps:
-- 1. Update Django models to match this schema
-- 2. Create Django migrations
-- 3. Update serializers and views
-- 4. Test RLS policies
-- 5. Update frontend to support business workflows
-- ============================================================================
