-- SQL Query to align Supabase Schema with Django Models
-- Run this in your Supabase SQL Editor to fix connection issues

-- 1. Ensure ChefOnboarding table has the correct structure
-- The crash was caused by 'status' vs 'identity_verification_status' mismatch.

CREATE TABLE IF NOT EXISTS public.chefs_chefonboarding (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES auth.users(id) DEFERRABLE INITIALLY DEFERRED, -- Assuming linked to auth.users or public.users
    culinary_paths jsonb NULL DEFAULT '[]'::jsonb,
    specialties jsonb NULL DEFAULT '[]'::jsonb,
    experience_level character varying(50) NULL,
    portfolio_media jsonb NULL DEFAULT '[]'::jsonb,
    availability_options jsonb NULL DEFAULT '[]'::jsonb,
    pricing_tier character varying(50) NULL,
    certifications jsonb NULL DEFAULT '[]'::jsonb,
    identity_verification_status character varying(20) NOT NULL DEFAULT 'pending',
    completed boolean NOT NULL DEFAULT false,
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT chefs_chefonboarding_user_id_key UNIQUE (user_id)
);

-- If the table already exists, ensuring the column exists:
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='chefs_chefonboarding' AND column_name='identity_verification_status') THEN
        ALTER TABLE public.chefs_chefonboarding ADD COLUMN identity_verification_status character varying(20) NOT NULL DEFAULT 'pending';
    END IF;
    
    -- If the old 'status' column exists and you want to migrate data or drop it:
    -- ALTER TABLE public.chefs_chefonboarding DROP COLUMN IF EXISTS status;
END $$;


-- 2. Ensure ChefProfile table exists (Core for Admin Dashboard)
CREATE TABLE IF NOT EXISTS public.chefs_chefprofile (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES auth.users(id) DEFERRABLE INITIALLY DEFERRED,
    bio text NULL,
    specialties jsonb NULL DEFAULT '[]'::jsonb,
    experience_level character varying(20) NOT NULL DEFAULT 'beginner',
    years_of_experience integer NOT NULL CHECK (years_of_experience >= 0),
    hourly_rate numeric(8, 2) NOT NULL DEFAULT 0.00,
    service_radius integer NOT NULL DEFAULT 10,
    address text NULL,
    city character varying(100) NULL,
    state character varying(100) NULL,
    zip_code character varying(20) NULL,
    latitude numeric(9, 6) NULL,
    longitude numeric(9, 6) NULL,
    is_verified boolean NOT NULL DEFAULT false,
    background_check_completed boolean NOT NULL DEFAULT false,
    average_rating numeric(3, 2) NOT NULL DEFAULT 0.00,
    total_reviews integer NOT NULL DEFAULT 0,
    total_bookings integer NOT NULL DEFAULT 0,
    is_available boolean NOT NULL DEFAULT true,
    availability_schedule jsonb NULL DEFAULT '{}'::jsonb,
    portfolio_images jsonb NULL DEFAULT '[]'::jsonb,
    certifications jsonb NULL DEFAULT '[]'::jsonb,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT chefs_chefprofile_user_id_key UNIQUE (user_id)
);

-- 3. Ensure other Admin-critical tables exist
-- Payments
CREATE TABLE IF NOT EXISTS public.payments_payment (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id bigint NULL, -- Relates to bookings table
    client_id bigint NULL,
    amount numeric(10, 2) NOT NULL,
    currency character varying(3) NOT NULL DEFAULT 'KES',
    status character varying(20) NOT NULL DEFAULT 'pending',
    payment_method character varying(50) NOT NULL DEFAULT 'mpesa',
    transaction_id character varying(100) NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now()
);

-- Payouts
CREATE TABLE IF NOT EXISTS public.payments_chefpayout (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chef_id bigint NOT NULL,
    booking_id bigint NOT NULL,
    amount numeric(10, 2) NOT NULL,
    currency character varying(3) NOT NULL DEFAULT 'KES',
    status character varying(20) NOT NULL DEFAULT 'pending',
    processed_at timestamp with time zone NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now()
);

-- Grant permissions to authenticated users and service role
GRANT ALL ON TABLE public.chefs_chefonboarding TO service_role;
GRANT ALL ON TABLE public.chefs_chefprofile TO service_role;
GRANT ALL ON TABLE public.payments_payment TO service_role;
GRANT ALL ON TABLE public.payments_chefpayout TO service_role;

GRANT ALL ON TABLE public.chefs_chefonboarding TO authenticated;
GRANT ALL ON TABLE public.chefs_chefprofile TO authenticated;
