# Generated by Django 5.2.8 on 2026-01-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="servings",
            field=models.PositiveIntegerField(
                default=4, help_text="Number of servings"
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="supabase_id",
            field=models.UUIDField(
                blank=True, help_text="Supabase record ID", null=True
            ),
        ),
    ]
