# Generated by Django 5.0.7 on 2025-10-21 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('recommendation_accuracy', 'Recommendation Accuracy'), ('user_satisfaction', 'User Satisfaction'), ('response_time', 'Response Time'), ('token_usage', 'Token Usage'), ('error_rate', 'Error Rate')], max_length=30)),
                ('metric_value', models.FloatField()),
                ('metric_data', models.JSONField(blank=True, default=dict)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('chef', 'Chef Recommendation'), ('menu', 'Menu Recommendation'), ('cuisine', 'Cuisine Recommendation'), ('meal_plan', 'Meal Plan Recommendation')], max_length=20)),
                ('user_preferences', models.JSONField(blank=True, default=dict)),
                ('dietary_restrictions', models.JSONField(blank=True, default=list)),
                ('budget_range', models.JSONField(blank=True, default=dict)),
                ('occasion', models.CharField(blank=True, max_length=100)),
                ('location', models.JSONField(blank=True, default=dict)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('reasoning', models.TextField(blank=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('feedback_rating', models.PositiveIntegerField(blank=True, null=True)),
                ('feedback_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'User'), ('ai', 'AI Assistant'), ('system', 'System')], max_length=10)),
                ('content', models.TextField()),
                ('ai_model_version', models.CharField(blank=True, max_length=50)),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('processing_time', models.FloatField(default=0.0)),
                ('message_metadata', models.JSONField(blank=True, default=dict)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('general', 'General Chat'), ('menu_planning', 'Menu Planning'), ('chef_discovery', 'Chef Discovery'), ('dietary_advice', 'Dietary Advice'), ('cooking_tips', 'Cooking Tips')], default='general', max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('context_data', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPreferenceLearning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_cuisines', models.JSONField(blank=True, default=dict)),
                ('dietary_patterns', models.JSONField(blank=True, default=dict)),
                ('price_sensitivity', models.FloatField(default=0.5)),
                ('booking_patterns', models.JSONField(blank=True, default=dict)),
                ('chef_preferences', models.JSONField(blank=True, default=dict)),
                ('interaction_count', models.PositiveIntegerField(default=0)),
                ('last_learning_update', models.DateTimeField(auto_now=True)),
                ('confidence_level', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
