# Generated by Django 5.2.8 on 2026-03-26 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0001_initial"),
        ("chefs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="chef",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="chefs.chefprofile",
            ),
        ),
    ]
