# Generated by Django 5.0.7 on 2025-10-21 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('chefs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='chef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='chefs.chefprofile'),
        ),
    ]
