# Generated by Django 5.0.7 on 2025-10-21 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_initial'),
        ('chefs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingmenuitem',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_menu_items', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='chef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='chefs.chefprofile'),
        ),
        migrations.AddField(
            model_name='bookingmenuitem',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.menuitem'),
        ),
        migrations.AlterUniqueTogether(
            name='bookingmenuitem',
            unique_together={('booking', 'menu_item')},
        ),
    ]
