# Generated by Django 5.2.8 on 2026-03-27 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_initial"),
        ("chefs", "0003_chefprofile_culinary_paths_and_identity"),
        ("experiences", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("pending_assignment", "Pending Assignment"),
                    ("pending_chef_acceptance", "Pending Chef Acceptance"),
                    ("confirmed", "Confirmed"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("refunded", "Refunded"),
                ],
                default="pending",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="BookingAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tier", models.PositiveSmallIntegerField(default=1)),
                ("notified_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sla_deadline",
                    models.DateTimeField(help_text="Auto-rotate after this time"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Notified — Awaiting Response"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("expired", "SLA Expired — Auto-rotated"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="bookings.booking",
                    ),
                ),
                (
                    "chef",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking_assignments",
                        to="chefs.chefprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "booking assignment",
                "verbose_name_plural": "booking assignments",
                "ordering": ["-notified_at"],
            },
        ),
        migrations.CreateModel(
            name="ChefMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("image", models.URLField(blank=True, max_length=500)),
                ("highlights", models.JSONField(blank=True, default=list)),
                (
                    "pricing_rules",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="guest_tiers, labour_fee, event_multiplier",
                    ),
                ),
                ("min_guests", models.PositiveIntegerField(default=1)),
                ("max_guests", models.PositiveIntegerField(default=20)),
                ("is_approved", models.BooleanField(default=False)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_menus",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "chef",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="v4_menus",
                        to="chefs.chefprofile",
                    ),
                ),
                (
                    "experience",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menus",
                        to="experiences.experience",
                    ),
                ),
            ],
            options={
                "verbose_name": "chef menu",
                "verbose_name_plural": "chef menus",
                "ordering": ["-created_at"],
            },
        ),
    ]
