# Generated by Django 5.0.7 on 2026-03-29 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_v4_chef_menu_and_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='v4_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='bookings.chefmenu'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='calories',
            field=models.PositiveIntegerField(blank=True, help_text='Estimated calories (kcal)', null=True),
        ),
    ]
