# Generated by Django 5.0.7 on 2026-03-30 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_v4_menu_menuitem_calories'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='confirmed_by_client_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
