# Generated by Django 5.0.7 on 2026-04-01 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_confirmed_by_client_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='external_payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('not_required', 'Not Required')], default='not_required', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_mode',
            field=models.CharField(choices=[('full_escrow', 'Full Escrow'), ('deposit_only', 'Deposit Only')], default='full_escrow', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pending_assignment', 'Pending Assignment'), ('pending_chef_acceptance', 'Pending Chef Acceptance'), ('confirmed', 'Confirmed'), ('deposit_paid', 'Deposit Paid'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=30),
        ),
    ]
