# Generated by Django 5.0.7 on 2025-12-05 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_add_meal_prep_to_menuitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at'], 'verbose_name': 'booking', 'verbose_name_plural': 'bookings'},
        ),
        migrations.AlterModelOptions(
            name='bookingmenuitem',
            options={'verbose_name': 'booking menu item', 'verbose_name_plural': 'booking menu items'},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['category', 'name'], 'verbose_name': 'menu item', 'verbose_name_plural': 'menu items'},
        ),
    ]
