# Generated by Django 6.0.1 on 2026-01-25 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "bookings",
            "0007_alter_booking_options_alter_bookingmenuitem_options_and_more",
        ),
        ("chefs", "0006_chefonboarding"),
        ("users", "0007_businessaccount_alter_clientprofile_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="client",
        ),
        migrations.AddField(
            model_name="booking",
            name="business",
            field=models.ForeignKey(
                blank=True,
                db_column="business_id",
                help_text="Business account - mutually exclusive with client_user",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="users.businessaccount",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="client_user",
            field=models.ForeignKey(
                blank=True,
                db_column="client_user_id",
                help_text="Individual client - mutually exclusive with business",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="individual_bookings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("business__isnull", True), ("client_user__isnull", False)
                    ),
                    models.Q(
                        ("business__isnull", False), ("client_user__isnull", True)
                    ),
                    _connector="OR",
                ),
                name="booking_must_have_client_or_business",
            ),
        ),
        migrations.AlterModelTable(
            name="booking",
            table="bookings_booking",
        ),
    ]
